afiliados_new:
    pattern:  /new
    defaults: { _controller: "DsgagenciaBundle:Afiliados:new" }
    
afiliados_create:
    pattern: /create
    defaults: { _controller: "DsgagenciaBundle:Afiliados:create" }
    requirements: { _method: post }
    
afiliados_sinActivar:
    pattern: /sinActivar
    defaults: { _controller: "DsgagenciaBundle:Afiliados:sinActivar" }