<?php

namespace Dsg\agenciaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
    public function getTrabajosCategorias()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT c FROM DsgagenciaBundle:Categoria c LEFT JOIN c.trabajos j WHERE j.finaliza > :date'
        )->setParameter('date', date('Y-m-d H:i:s', time()));
 
        return $query->getResult();
    }   
}
