# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
 
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: /admin/dashboard
            logout:
                path: /logout
                target: /
 
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
 
    providers:
        main:
            entity: { class: Dsg\agenciaBundle\Entity\Usuarios, property: username }
 
    encoders:
        Dsg\agenciaBundle\Entity\Usuarios: sha512
