services:
    dsg.agencia.admin.categoria:
        class: Dsg\agenciaBundle\Admin\CategoriaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dsg, label: Categorias }
        arguments:
            - ~
            - Dsg\agenciaBundle\Entity\Categoria
            - 'DsgagenciaBundle:CategoriaAdmin'
 
    Dsg.agencia.admin.trabajos:
        class: Dsg\agenciaBundle\Admin\TrabajosAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dsg, label: Trabajos }
        arguments:
            - ~
            - Dsg\agenciaBundle\Entity\Trabajos
            - 'DsgagenciaBundle:TrabajosAdmin'